# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_open_window(object):
    def setupUi(self, open_window):
        open_window.setObjectName("open_window")
        open_window.resize(519, 541)
        self.centralwidget = QtWidgets.QWidget(open_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 350, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 420, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(103, 186, 128);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 170, 121, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Users/секси няшка/Desktop/Мастер пол.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        open_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(open_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 26))
        self.menubar.setObjectName("menubar")
        open_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(open_window)
        self.statusbar.setObjectName("statusbar")
        open_window.setStatusBar(self.statusbar)

        self.retranslateUi(open_window)
        QtCore.QMetaObject.connectSlotsByName(open_window)

    def retranslateUi(self, open_window):
        _translate = QtCore.QCoreApplication.translate
        open_window.setWindowTitle(_translate("open_window", "MainWindow"))
        self.label_3.setText(_translate("open_window", "Добро пожаловать"))
        self.label_4.setText(_translate("open_window", "Мастер Пол"))
        self.pushButton_2.setText(_translate("open_window", "Запустить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    open_window = QtWidgets.QMainWindow()
    ui = Ui_open_window()
    ui.setupUi(open_window)
    open_window.show()
    sys.exit(app.exec_())
